# Generated by Django 6.0.6 on 2026-06-24 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reclamation', models.CharField(blank=True, max_length=50)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(blank=True, max_length=30)),
                ('canal', models.CharField(blank=True, max_length=30)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('delai_traitement', models.PositiveIntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='clients.client')),
                ('direction_regionale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='core.directionregionale')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'db_table': 'complaints_reclamation',
            },
        ),
    ]
