# Generated by Django 6.0.6 on 2026-06-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reclamation',
            options={'verbose_name': 'Réclamation HT', 'verbose_name_plural': 'Réclamations HT'},
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='motif',
        ),
        migrations.AddField(
            model_name='reclamation',
            name='acteur_traitement',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='agence',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='auteur_cloture',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='auteur_creation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='branchement',
            field=models.CharField(blank=True, max_length=20, verbose_name='Branchement / Adresse technique'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='contact',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='date_modification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='date_verification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='delai_contractuel_traitement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='delai_contractuel_verification',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='delai_verification',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='ecart_traitement',
            field=models.IntegerField(blank=True, null=True, verbose_name='Écart traitement (réel - contractuel)'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='ecart_verification',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='groupe_destinataire',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='identifiant_contrat',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='motif_modification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='motif_retablissement',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='nature_reclamation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='nom_client',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='nombre_relances',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='numero_sollicitation',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='partenaire',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='priorite',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='rapport_creation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='rapport_traitement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='rapport_verification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='segment_client',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='sous_segment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='sous_typologie',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='statut_client',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='type_client',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='type_sollicitation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='typologie_reclamation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='delai_traitement',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Délai de traitement (jours)'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='type_reclamation',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
