# Generated by Django 6.0.6 on 2026-06-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_extended_reclamation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='date_cloture',
            field=models.DateField(blank=True, null=True, verbose_name='Date de traitement'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='date_modification',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='date_verification',
            field=models.DateField(blank=True, null=True),
        ),
    ]
