# Generated by Django 6.0.6 on 2026-06-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionRegionale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('code_numerique', models.PositiveSmallIntegerField(unique=True)),
                ('zone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Direction régionale',
                'verbose_name_plural': 'Directions régionales',
                'ordering': ['code_numerique'],
            },
        ),
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Entité',
                'verbose_name_plural': 'Entités',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField()),
                ('mois', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Période',
                'verbose_name_plural': 'Périodes',
                'ordering': ['annee', 'mois'],
                'unique_together': {('annee', 'mois')},
            },
        ),
    ]
