# Generated by Django 6.0.6 on 2026-06-25 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entite',
            options={'ordering': ['niveau', 'libelle'], 'verbose_name': 'Entité', 'verbose_name_plural': 'Entités'},
        ),
        migrations.AddField(
            model_name='entite',
            name='niveau',
            field=models.CharField(choices=[('direction', 'Direction'), ('sous_direction', 'Sous-Direction'), ('service', 'Service')], default='service', max_length=20),
        ),
        migrations.AddField(
            model_name='entite',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enfants', to='core.entite'),
        ),
    ]
