# Generated by Django 6.0.6 on 2026-06-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_entite_options_entite_niveau_entite_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionregionale',
            name='libelle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
