# Generated by Django 6.0.6 on 2026-06-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_directionregionale_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='entite',
            name='objectif_ca_mensuel_mds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Objectif de CA mensuel (Mds FCFA)'),
        ),
        migrations.AddField(
            model_name='entite',
            name='seuil_recouvrement_orange',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='Seuil "orange" du taux de recouvrement (ex: 0.950)'),
        ),
        migrations.AddField(
            model_name='entite',
            name='seuil_recouvrement_vert',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='Seuil "vert" du taux de recouvrement (ex: 0.990)'),
        ),
    ]
