# Generated by Django 6.0.6 on 2026-07-02 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_entite_objectif_ca_mensuel_mds_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicateur', models.CharField(choices=[('ca_mensuel', 'CA mensuel (Mds FCFA)'), ('taux_recouvrement', 'Taux de recouvrement (%)'), ('taux_completion', 'Taux de complétion des fiches (%)'), ('taux_conversion_cie', 'Taux de conversion Guichet Unique → CIE (%)'), ('delai_raccordement', 'Délai moyen de raccordement (jours)')], max_length=30)),
                ('valeur_cible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('defini_le', models.DateTimeField(auto_now=True)),
                ('defini_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectifs_definis', to=settings.AUTH_USER_MODEL)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='core.entite')),
            ],
            options={
                'verbose_name': 'Objectif',
                'verbose_name_plural': 'Objectifs',
                'ordering': ['entite__libelle', 'indicateur'],
                'unique_together': {('entite', 'indicateur')},
            },
        ),
    ]
