# Generated by Django 6.0.6 on 2026-06-27 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_directionregionale_libelle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmeubleProspecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField(blank=True, null=True)),
                ('nom_structure', models.CharField(max_length=255)),
                ('constructeur', models.CharField(blank=True, max_length=255)),
                ('type_cible', models.CharField(blank=True, choices=[('sci', 'SCI'), ('immeuble', 'Immeuble'), ('promoteur', 'Promoteur immobilier')], max_length=20)),
                ('interlocuteur', models.CharField(blank=True, max_length=255)),
                ('fonction_interlocuteur', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('situation_geographique', models.CharField(blank=True, max_length=255)),
                ('zone_prospection', models.CharField(blank=True, max_length=100)),
                ('type_construction', models.CharField(blank=True, choices=[('immeuble', 'Immeuble'), ('villa', 'Villa'), ('mixte', 'Mixte')], max_length=20)),
                ('nb_niveaux', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nb_appartements_bureaux', models.PositiveIntegerField(blank=True, null=True)),
                ('details_construction', models.CharField(blank=True, max_length=255)),
                ('stade_avancement', models.CharField(blank=True, choices=[('terrassement', 'Terrassement'), ('gros_oeuvre', 'Gros œuvre'), ('finition', 'Finition')], max_length=20)),
                ('date_debut_travaux', models.DateField(blank=True, null=True)),
                ('date_prev_fin_travaux', models.DateField(blank=True, null=True)),
                ('delai_livraison', models.CharField(blank=True, max_length=20)),
                ('poste_existant', models.BooleanField(blank=True, null=True)),
                ('montant_bra_paye', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observations', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects_geres', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects_crees', to=settings.AUTH_USER_MODEL)),
                ('direction_regionale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immeubles_prospectes', to='core.directionregionale')),
            ],
            options={
                'verbose_name': 'Immeuble prospecté',
                'verbose_name_plural': 'Immeubles prospectés',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='DemarcheAdministrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisme', models.CharField(choices=[('cie', 'CIE'), ('sodeci', 'SODECI')], max_length=10)),
                ('demande_initiee', models.BooleanField(default=False)),
                ('type_demande', models.CharField(blank=True, choices=[('raccordement', 'Raccordement'), ('branchement', 'Branchement'), ('compteur_chantier', 'Compteur chantier')], max_length=20)),
                ('statut', models.CharField(blank=True, choices=[('non_initie', 'Non-initié'), ('depose', 'Déposé'), ('en_traitement', 'En traitement'), ('traite', 'Traité'), ('non_conforme', 'Non-conforme')], max_length=20)),
                ('numero_demande', models.CharField(blank=True, max_length=50)),
                ('details_non_conformite', models.TextField(blank=True)),
                ('immeuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demarches', to='prospection.immeubleprospecte')),
            ],
            options={
                'verbose_name': 'Démarche administrative',
                'verbose_name_plural': 'Démarches administratives',
                'unique_together': {('immeuble', 'organisme')},
            },
        ),
    ]
