# Generated by Django 6.0.6 on 2026-06-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='immeubleprospecte',
            name='dex',
            field=models.CharField(blank=True, choices=[('abidjan', 'Abidjan'), ('interieur', 'Intérieur')], max_length=20, verbose_name='DEX (Abidjan/Intérieur)'),
        ),
    ]
