# Generated by Django 6.0.6 on 2026-06-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospection', '0002_immeubleprospecte_dex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immeubleprospecte',
            name='date_debut_travaux',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='immeubleprospecte',
            name='date_prev_fin_travaux',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
