# Generated by Django 6.0.6 on 2026-06-30 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospection', '0003_alter_immeubleprospecte_date_debut_travaux_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='immeubleprospecte',
            name='ccgc_nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='CCGC (source brute)'),
        ),
        migrations.CreateModel(
            name='OperateurImmobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=150)),
                ('ccgc', models.CharField(blank=True, choices=[('BOGA', 'Mme BOGA'), ('DIOMANDE', 'Mme DIOMANDE'), ('SYLLA', 'Mme SYLLA')], max_length=20, verbose_name='CCGC responsable')),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operateurs_geres', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur CCGC')),
            ],
            options={
                'verbose_name': 'Opérateur immobilier',
                'verbose_name_plural': 'Opérateurs immobiliers',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='immeubleprospecte',
            name='operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immeubles', to='prospection.operateurimmobilier'),
        ),
    ]
