# Generated by Django 6.0.6 on 2026-07-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospection', '0004_immeubleprospecte_ccgc_nom_operateurimmobilier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operateurimmobilier',
            name='projet_2026',
            field=models.BooleanField(default=False, verbose_name='Projet clé confirmé 2026'),
        ),
        migrations.AddField(
            model_name='operateurimmobilier',
            name='segment',
            field=models.CharField(choices=[('standard', 'Standard'), ('prioritaire', 'Prioritaire'), ('top', 'Top opérateur')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='operateurimmobilier',
            name='sensible',
            field=models.BooleanField(default=False, verbose_name='Opérateur sensible / stratégique'),
        ),
        migrations.AddField(
            model_name='operateurimmobilier',
            name='zone',
            field=models.CharField(blank=True, max_length=150, verbose_name='Zone de prospection'),
        ),
    ]
