# Generated by Django 6.0.6 on 2026-07-02 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospection', '0005_operateurimmobilier_projet_2026_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitePlanifiee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField()),
                ('trimestre', models.CharField(choices=[('T3', 'T3 (Juil.-Août-Sept.)'), ('T4', 'T4 (Oct.-Nov.-Déc.)')], max_length=2)),
                ('mois_prevu', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mois prévu (1-12)')),
                ('date_prevue', models.DateField(blank=True, null=True)),
                ('date_realisee', models.DateField(blank=True, null=True)),
                ('compte_rendu', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visites_planifiees', to=settings.AUTH_USER_MODEL)),
                ('immeuble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visites_planifiees', to='prospection.immeubleprospecte')),
                ('operateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visites_planifiees', to='prospection.operateurimmobilier')),
            ],
            options={
                'verbose_name': 'Visite planifiée',
                'verbose_name_plural': 'Visites planifiées',
                'ordering': ['-annee', '-trimestre', 'mois_prevu'],
            },
        ),
    ]
