# Generated by Django 6.0.6 on 2026-07-03 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_objectif'),
        ('prospection', '0006_visiteplanifiee'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiteplanifiee',
            name='commune_quartier',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='visiteplanifiee',
            name='direction_regionale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visites_planifiees', to='core.directionregionale'),
        ),
    ]
