"""Nomenclature officielle secteur/branche d'activité, valeurs réelles extraites
de data/V_Fait_Fact_HT_DCB.xlsx (colonnes Secteur_Activité/Branche_Activité),
PAS inventées : ce sont les libellés exacts déjà utilisés dans les imports
existants (cf. importers.import_clients_abonnements). Les ".." en fin de valeur
sont tels que dans la source (probablement une troncature Excel d'origine),
conservés à l'identique pour rester cohérent avec les ~5 200 clients déjà
importés avec ces valeurs exactes ; seul le libellé affiché (2e élément du
tuple) est nettoyé pour la lisibilité dans les formulaires.

4 branches ("CHAUSSURES EN CUIR..", "CONST ET REP DENG TRACT..",
"INDUSTRIES DU TABAC..", "TOURTAUX OLEAGINEUX..") ajoutées après vérification
croisée avec data/V_Fait_Detail_Fact_HT.xlsx (périmètre Business plus large,
CENTREGEST=1) : absentes de V_Fait_Fact_HT_DCB.xlsx mais bien réelles."""

SECTEUR_ACTIVITE_CHOICES = [
    ('ADMINISTRATIONS..', 'Administrations'),
    ('ADMISTRATIONS PRIVEES..', 'Admistrations Privees'),
    ('AGR INDUST EXPORT..', 'Agr Indust Export'),
    ('AGR VIVR ELEV CHASSE..', 'Agr Vivr Elev Chasse'),
    ('AUTRES INDUSTRIE ALIMENTAIRE..', 'Autres Industrie Alimentaire'),
    ('AUTRES SERV PRIVES..', 'Autres Serv Prives'),
    ('BATIMENT ET T.P...', 'Batiment Et T.P'),
    ('BOISSONS ET GLACE ALIMENTAIRE..', 'Boissons Et Glace Alimentaire'),
    ('BRANCHE ACTIV EXTRACTION..', 'Branche Activ Extraction'),
    ('BRANCHE INDUSTRIES BOIS..', 'Branche Industries Bois'),
    ('BRANCHES INDUSTRIES CHIMIQUES..', 'Branches Industries Chimiques'),
    ('COMMERCES..', 'Commerces'),
    ('CONSER PREPAR ALIMENT..', 'Conser Prepar Aliment'),
    ('CONSTR ET REPAR MATE TRANSPORT..', 'Constr Et Repar Mate Transport'),
    ('CORPS ALIMENTAIRES..', 'Corps Alimentaires'),
    ('CUIR ET ARTICLESS CHAUSSANTS..', 'Cuir Et Articless Chaussants'),
    ('ENERGIE ELECT GAZ EAU..', 'Energie Elect Gaz Eau'),
    ('EXPL FORESTIERE..', 'Expl Forestiere'),
    ('IND DIVERSES..', 'Ind Diverses'),
    ('IND MECANIQUES ELECTRIQUES..', 'Ind Mecaniques Electriques'),
    ('INDUSTRIES DU CAOUTCHOUC..', 'Industries Du Caoutchouc'),
    ('INSTITUTIONS FINANCIERES..', 'Institutions Financieres'),
    ('LOCAT GEST BATIMENTS..', 'Locat Gest Batiments'),
    ('MATERIAUX CONSTR VERRE..', 'Materiaux Constr Verre'),
    ('PECHE..', 'Peche'),
    ('RAFFINERIE PETROLE..', 'Raffinerie Petrole'),
    ('REPRESENTATIONS DIPLOMATIQUES..', 'Representations Diplomatiques'),
    ('SERVICES DOMESTIQUES..', 'Services Domestiques'),
    ('SERVICES PUBLICS..', 'Services Publics'),
    ('SIDERURGIE ET 1ER TRANS METAUX..', 'Siderurgie Et 1Er Trans Metaux'),
    ('TEXTILLES ET HABILLEMENT..', 'Textilles Et Habillement'),
    ('TRANSPORT TELECOM..', 'Transport Telecom'),
    ('TRAVAIL DES GRAINS ET FARINE..', 'Travail Des Grains Et Farine'),
]

BRANCHE_ACTIVITE_CHOICES = [
    ('1ERE TRANSFORMATION..', '1Ere Transformation'),
    ('ADMINISTRATIONS..', 'Administrations'),
    ('ADMISTRATIONS PRIVEES..', 'Admistrations Privees'),
    ('AGENTS D ASSURANCES..', 'Agents D Assurances'),
    ('AGR INDUST EXPORT..', 'Agr Indust Export'),
    ('AGR VIVR ELEV CHASSE..', 'Agr Vivr Elev Chasse'),
    ('ALIMENTS POUR ANIMAUX..', 'Aliments Pour Animaux'),
    ('ARTICLES DHABILLEMENT..', 'Articles Dhabillement'),
    ('ASSURANCES..', 'Assurances'),
    ('AUTRES ADMINISTRATIONS PRIVEES..', 'Autres Administrations Privees'),
    ('AUTRES ARTICLES..', 'Autres Articles'),
    ('AUTRES ETS FINANCIERS..', 'Autres Ets Financiers'),
    ('AUTRES INDUSTRIE ALIMENTAIRE..', 'Autres Industrie Alimentaire'),
    ('AUTRES INDUSTRIES MANUF..', 'Autres Industries Manuf'),
    ('AUTRES PRODUITS ALIMENTAIRES..', 'Autres Produits Alimentaires'),
    ('AUTRES PRODUITS CHIMIQUES..', 'Autres Produits Chimiques'),
    ('AUTRES SERV PRIVES..', 'Autres Serv Prives'),
    ('AUTRES..', 'Autres'),
    ('BANQUES........', 'Banques'),
    ('BATIMENT ET T.P...', 'Batiment Et T.P'),
    ('BIERRE..', 'Bierre'),
    ('BISCUTERIE..', 'Biscuterie'),
    ('BOISSONS ET GLACE ALIMENTAIRE..', 'Boissons Et Glace Alimentaire'),
    ('BOISSONS HYGIENIQUES..', 'Boissons Hygieniques'),
    ('BONNETERIE..', 'Bonneterie'),
    ('BOULANGERIE PATISSERIE..', 'Boulangerie Patisserie'),
    ('BOUTIQUES SUPER-MARCHES..', 'Boutiques Super-Marches'),
    ('BRANCHE ACTIV EXTRACTION..', 'Branche Activ Extraction'),
    ('BRANCHE INDUSTRIES BOIS..', 'Branche Industries Bois'),
    ('BRANCHES INDUSTRIES CHIMIQUES..', 'Branches Industries Chimiques'),
    ('C.N DE PREV SOCIALE..', 'C.N De Prev Sociale'),
    ('CAISSE DE STAB ET MECANO..', 'Caisse De Stab Et Mecano'),
    ('CAOUTCHOUC NATUREL..', 'Caoutchouc Naturel'),
    ('CHAUSSURES EN PLASTIQUE..', 'Chaussures En Plastique'),
    ('CIMENTS CHAUX PLATRE..', 'Ciments Chaux Platre'),
    ('COMMERCES..', 'Commerces'),
    ('COMMUNES..', 'Communes'),
    ('COMMUNICATION..', 'Communication'),
    ('CONDIMENTS PREPARES..', 'Condiments Prepares'),
    ('CONSER PREPAR ALIMENT..', 'Conser Prepar Aliment'),
    ('CONSERVES POISSON..', 'Conserves Poisson'),
    ('CONST ET REP AUTRE MATE.TRANSP..', 'Const Et Rep Autre Mate.Transp'),
    ('CONST ET REP CYCL ET MOT..', 'Const Et Rep Cycl Et Mot'),
    ('CONST ET REP DAUTOMOBILES..', 'Const Et Rep Dautomobiles'),
    ('CONSTR ET REPAR MATE TRANSPORT..', 'Constr Et Repar Mate Transport'),
    ('CORPS ALIMENTAIRES..', 'Corps Alimentaires'),
    ('CUIR ET ARTICLESS CHAUSSANTS..', 'Cuir Et Articless Chaussants'),
    ('DECORTICAGE DU CAFE..', 'Decorticage Du Cafe'),
    ('DERIVES DU DU PETROLE..', 'Derives Du Du Petrole'),
    ('EAU..', 'Eau'),
    ('EGRENAGE DU COTON..', 'Egrenage Du Coton'),
    ('ELEVAGE..', 'Elevage'),
    ('ENERGIE ELECT GAZ EAU..', 'Energie Elect Gaz Eau'),
    ('ENERGIE ELECTRIQUE..', 'Energie Electrique'),
    ('ENERGIE ET 1ERE TRANS METAUX..', 'Energie Et 1Ere Trans Metaux'),
    ('ENSEIGNEMENTS..', 'Enseignements'),
    ('ENTREP CONST BATIMENT..', 'Entrep Const Batiment'),
    ('ENTREP DES TP..', 'Entrep Des Tp'),
    ('ENTREP MAISONS PREFABRIQUES..', 'Entrep Maisons Prefabriques'),
    ('ENTREPOTS ET CONDIT PRODUITS..', 'Entrepots Et Condit Produits'),
    ('EXPL FORESTIERE..', 'Expl Forestiere'),
    ('FABRIC. CHAUSSURES..', 'Fabric. Chaussures'),
    ('FABRICATION ENGRAIS..', 'Fabrication Engrais'),
    ('FABRICATION-INDUSTRIE DOEUVRE..', 'Fabrication-Industrie Doeuvre'),
    ('FILATURE TISSAGE TEINTURE..', 'Filature Tissage Teinture'),
    ('FRUIT ET JUS..', 'Fruit Et Jus'),
    ('GAZ LIQUEFIES..', 'Gaz Liquefies'),
    ('GESTION BATIMENT..', 'Gestion Batiment'),
    ('GLACE ALIMENTAIRE..', 'Glace Alimentaire'),
    ('GRES PORCELAINES ET FAIENCES..', 'Gres Porcelaines Et Faiences'),
    ('HUILES BRUTES ET PALMISTES..', 'Huiles Brutes Et Palmistes'),
    ('HUILES ESSENTIELLES..', 'Huiles Essentielles'),
    ('HUILES RAFFINEES..', 'Huiles Raffinees'),
    ('HYGIENE SANTE..', 'Hygiene Sante'),
    ('IMPRIMERIE ET ANNEXES..', 'Imprimerie Et Annexes'),
    ('IND DIVERSES..', 'Ind Diverses'),
    ('IND MECANIQUES ELECTRIQUES..', 'Ind Mecaniques Electriques'),
    ('INDUSTRIE DU SUCRE..', 'Industrie Du Sucre'),
    ('INDUSTRIE DU VERRE..', 'Industrie Du Verre'),
    ('INDUSTRIES DU CAOUTCHOUC..', 'Industries Du Caoutchouc'),
    ('INSTITUTIONS FINANCIERES..', 'Institutions Financieres'),
    ('LAIT..', 'Lait'),
    ('LOCAT GEST BATIMENTS..', 'Locat Gest Batiments'),
    ('LOCAT MACHINES ET ORDINAT..', 'Locat Machines Et Ordinat'),
    ('MACHINES ET FOURNIT ELECTRIQUE..', 'Machines Et Fournit Electrique'),
    ('MATER DE CONSTRUC EN TERRE..', 'Mater De Construc En Terre'),
    ('MATERIAUX CONSTR VERRE..', 'Materiaux Constr Verre'),
    ('MATERIAUX DE CONSTRUCTION..', 'Materiaux De Construction'),
    ('MECANIQUE DE PRECISION..', 'Mecanique De Precision'),
    ('MINERAI NON FERREUX..', 'Minerai Non Ferreux'),
    ('MOUSSE DE LATEX..', 'Mousse De Latex'),
    ('OUVRAGE EN BOIS..', 'Ouvrage En Bois'),
    ('OUVRAGE EN PIERRE..', 'Ouvrage En Pierre'),
    ('OUVRAGES PLAST SAUF CHAUSS..', 'Ouvrages Plast Sauf Chauss'),
    ('OUVRAGES SIMPLES ET MATERIAUX..', 'Ouvrages Simples Et Materiaux'),
    ('PAPIER ET ARTICLES..', 'Papier Et Articles'),
    ('PARFUMERIE PRODUITS DE BEAUTE..', 'Parfumerie Produits De Beaute'),
    ('PECHE..', 'Peche'),
    ('PESTICIDES..', 'Pesticides'),
    ('PHARMACIES..', 'Pharmacies'),
    ('PNEUMATIQUES..', 'Pneumatiques'),
    ('PREMIERE TRANSFORMATION BOIS..', 'Premiere Transformation Bois'),
    ('PRESIDENCE SERVICES GOUVER..', 'Presidence Services Gouver'),
    ('PRODUCTION INDUSTRIE..', 'Production Industrie'),
    ('PRODUITS CHIMIQUES DE BASE..', 'Produits Chimiques De Base'),
    ('PRODUITS EN AMIANTE..', 'Produits En Amiante'),
    ('PRODUITS PHARMAC MEDICAMENTS..', 'Produits Pharmac Medicaments'),
    ('PRODUITS TIRES DU CACAO..', 'Produits Tires Du Cacao'),
    ('RAFFINERIE  SEL..', 'Raffinerie  Sel'),
    ('RAFFINERIE DE PETROLE..', 'Raffinerie De Petrole'),
    ('RAFFINERIE PETROLE..', 'Raffinerie Petrole'),
    ('REPRESENTATIONS DIPLOMATIQUES..', 'Representations Diplomatiques'),
    ('RESTAURANTS HOTELS..', 'Restaurants Hotels'),
    ('SAVONS ET LESSIVES..', 'Savons Et Lessives'),
    ('SERV DOMESTIQUES..', 'Serv Domestiques'),
    ('SERV PERSONNELS DIVERS..', 'Serv Personnels Divers'),
    ('SERV RECREATIFS ET CULTURELS..', 'Serv Recreatifs Et Culturels'),
    ('SERV SANTE..', 'Serv Sante'),
    ('SERVICE DIVERS..', 'Service Divers'),
    ('SERVICES DIVERS..', 'Services Divers'),
    ('SERVICES DOMESTIQUES..', 'Services Domestiques'),
    ('SERVICES JURIDIQUES CONSEIL..', 'Services Juridiques Conseil'),
    ('SERVICES PUBLICS..', 'Services Publics'),
    ('SIDERURGIE ET 1ER TRANS METAUX..', 'Siderurgie Et 1Er Trans Metaux'),
    ('STAT SERV ET STOCK PETROLE..', 'Stat Serv Et Stock Petrole'),
    ('TEXTILLES ET HABILLEMENT..', 'Textilles Et Habillement'),
    ('TRANSP AERIENS..', 'Transp Aeriens'),
    ('TRANSP FERROVIAIRES..', 'Transp Ferroviaires'),
    ('TRANSP MARIT ET LAGUNAIRES..', 'Transp Marit Et Lagunaires'),
    ('TRANSP ROUTIERS..', 'Transp Routiers'),
    ('TRANSPORT TELECOM..', 'Transport Telecom'),
    ('TRAVAIL DES GRAINS ET FARINE..', 'Travail Des Grains Et Farine'),
    ('USINAGE DE RIZ..', 'Usinage De Riz'),
    ('VERNIS PEINTURE LAQUES..', 'Vernis Peinture Laques'),
    ('VIANDES ET CONS VIANDES..', 'Viandes Et Cons Viandes'),
    ('VINS BOISSONS ALCOOLISES..', 'Vins Boissons Alcoolises'),
    ('CHAUSSURES EN CUIR..', 'Chaussures En Cuir'),
    ('CONST ET REP DENG TRACT..', 'Const Et Rep Deng Tract'),
    ('INDUSTRIES DU TABAC..', 'Industries Du Tabac'),
    ('TOURTAUX OLEAGINEUX..', 'Tourteaux Oleagineux'),
]

