# Generated by Django 6.0.6 on 2026-06-24 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeRaccordement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numdi', models.CharField(max_length=30)),
                ('typdi', models.CharField(max_length=5)),
                ('date_initiation', models.DateField(blank=True, null=True)),
                ('montant_demande', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('montant_net', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='clients.client')),
                ('direction_regionale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='core.directionregionale')),
            ],
            options={
                'verbose_name': 'Demande de raccordement',
                'verbose_name_plural': 'Demandes de raccordement',
                'db_table': 'connection_requests_demanderaccordement',
            },
        ),
        migrations.CreateModel(
            name='SuiviDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(blank=True, max_length=50)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('date_validation_devis', models.DateField(blank=True, null=True)),
                ('date_execution', models.DateField(blank=True, null=True)),
                ('duree_validation_devis', models.PositiveIntegerField(blank=True, null=True)),
                ('duree_totale', models.PositiveIntegerField(blank=True, null=True)),
                ('tranche_delai', models.CharField(blank=True, max_length=30)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suivi', to='demandes_raccordement.demanderaccordement')),
            ],
            options={
                'verbose_name': 'Suivi de demande',
                'verbose_name_plural': 'Suivis de demande',
                'db_table': 'connection_requests_suividemande',
            },
        ),
    ]
