# Generated by Django 6.0.6 on 2026-06-24 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idabon', models.CharField(max_length=20, unique=True)),
                ('nom_prenoms', models.CharField(blank=True, max_length=255)),
                ('secteur_activite', models.CharField(blank=True, max_length=100)),
                ('branche_activite', models.CharField(blank=True, max_length=100)),
                ('est_strategique', models.BooleanField(default=False)),
                ('direction_regionale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='core.directionregionale')),
                ('entite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='core.entite')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['idabon'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refraccord', models.CharField(blank=True, max_length=30)),
                ('typabon', models.CharField(blank=True, max_length=10)),
                ('posabon', models.CharField(blank=True, max_length=5)),
                ('psabon', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tranche_puissance', models.CharField(blank=True, max_length=30)),
                ('typcomptage', models.CharField(blank=True, max_length=20)),
                ('codtarif', models.CharField(blank=True, max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='clients.client')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
            },
        ),
    ]
