# Generated by Django 6.0.6 on 2026-06-27 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_charge_affaires'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='depart',
            field=models.CharField(blank=True, max_length=50, verbose_name='Départ HT'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='poste',
            field=models.CharField(blank=True, max_length=100, verbose_name='Poste source HT/MT'),
        ),
        migrations.AddField(
            model_name='client',
            name='a_contrat',
            field=models.BooleanField(blank=True, null=True, verbose_name='Contrat signé ?'),
        ),
        migrations.AddField(
            model_name='client',
            name='contrat_document',
            field=models.FileField(blank=True, null=True, upload_to='contrats_clients/', verbose_name='Contrat (archivage numérique)'),
        ),
        migrations.AddField(
            model_name='client',
            name='contrat_reference_physique',
            field=models.CharField(blank=True, max_length=100, verbose_name="Référence d'archivage physique (si pas de numérique)"),
        ),
        migrations.AddField(
            model_name='client',
            name='fiche_maj_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='fiche_maj_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_completees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='strategique_en_attente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='strategique_propose_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='strategique_propose_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propositions_strategiques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='strategique_valide_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='strategique_valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_strategiques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Interlocuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('representant_legal', 'Représentant légal'), ('technique', 'Interlocuteur technique (incident réseau)'), ('commercial', 'Interlocuteur commercial / facturation')], max_length=20)),
                ('nom', models.CharField(max_length=255)),
                ('fonction', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interlocuteurs', to='clients.client')),
            ],
            options={
                'verbose_name': 'Interlocuteur client',
                'verbose_name_plural': 'Interlocuteurs client',
                'ordering': ['client', 'role'],
            },
        ),
    ]
