# Generated by Django 6.0.6 on 2026-06-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_historiquefiche'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStrategiqueNonRattache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(blank=True, max_length=255)),
                ('identifiant_brut', models.CharField(blank=True, max_length=30, verbose_name='Identifiant (fichier source)')),
                ('direction', models.CharField(blank=True, max_length=100)),
                ('exploitation', models.CharField(blank=True, max_length=100)),
                ('interlocuteurs', models.CharField(blank=True, max_length=255)),
                ('fonction', models.CharField(blank=True, max_length=150)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('importe_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client stratégique non rattaché',
                'verbose_name_plural': 'Clients stratégiques non rattachés',
                'ordering': ['raison_sociale'],
            },
        ),
    ]
