# Generated by Django 6.0.6 on 2026-06-30 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_clientstrategiquenonrattache'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientstrategiquenonrattache',
            name='client_associe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflits_strategiques', to='clients.client'),
        ),
        migrations.AddField(
            model_name='clientstrategiquenonrattache',
            name='type_anomalie',
            field=models.CharField(choices=[('manquant', 'Identifiant manquant dans le fichier source'), ('introuvable', 'Identifiant introuvable dans la base de facturation'), ('ambigu', 'Identifiant déjà attribué à un autre client dans le fichier source')], default='introuvable', max_length=20),
        ),
    ]
