# Generated by Django 6.0.6 on 2026-06-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_clientstrategiquenonrattache_client_associe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.CharField(choices=[('dcb_file', 'Fichier DCB (maître)'), ('facturation', 'Facturation uniquement')], default='dcb_file', max_length=20),
        ),
    ]
