# Generated by Django 6.0.6 on 2026-07-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_client_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='source',
        ),
    ]
