# Generated by Django 6.0.6 on 2026-07-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_pad_idabon_8_chiffres'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='date_abonnement',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'abonnement"),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='numero_poste_client',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° poste client'),
        ),
        migrations.AddField(
            model_name='client',
            name='agence',
            field=models.CharField(blank=True, max_length=100, verbose_name='Exploitation / Agence'),
        ),
        migrations.AddField(
            model_name='client',
            name='dans_client_dcb',
            field=models.BooleanField(default=False, verbose_name='Présent dans le référentiel Client DCB'),
        ),
        migrations.AddField(
            model_name='client',
            name='dans_facturation',
            field=models.BooleanField(default=False, verbose_name='Présent dans la base de facturation'),
        ),
        migrations.AddField(
            model_name='client',
            name='groupe_electrogene_dispo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Groupe électrogène disponible ?'),
        ),
        migrations.AddField(
            model_name='client',
            name='groupe_electrogene_puissance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Puissance groupe électrogène (kVA)'),
        ),
        migrations.AddField(
            model_name='client',
            name='localisation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
