# Generated by Django 6.0.6 on 2026-07-02 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_abonnement_date_abonnement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fiche_controlee',
            field=models.BooleanField(default=False, verbose_name='Fiche contrôlée par le chef'),
        ),
        migrations.AddField(
            model_name='client',
            name='fiche_controlee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='fiche_controlee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_controlees', to=settings.AUTH_USER_MODEL),
        ),
    ]
