# Generated by Django 6.0.6 on 2026-06-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('directeur', 'Directeur'), ('sous_directeur', 'Sous-Directeur'), ('chef_service', 'Chef de Service'), ('charge_affaires', "Chargé d'Affaires")], max_length=20),
        ),
    ]
