# Generated by Django 6.0.6 on 2026-06-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('directeur', 'Directeur'), ('sous_directeur', 'Sous-Directeur'), ('chef_service', 'Chef de Service'), ('charge_affaires', "Chargé d'Affaires"), ('cadre_charge_affaires', "Cadre Chargée d'Affaires"), ('cadre_guichet_unique', 'Cadre Guichet Unique'), ('conseiller_grands_comptes', 'Conseiller Client Grands Comptes')], max_length=30),
        ),
    ]
