# Generated by Django 6.0.6 on 2026-06-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portee_individuelle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('directeur', 'Directeur'), ('sous_directeur', 'Sous-Directeur'), ('chef_service', 'Chef de Service'), ('responsable', 'Responsable'), ('cadre_charge_affaires', "Cadre Chargée d'Affaires"), ('cadre_guichet_unique', 'Cadre Guichet Unique'), ('conseiller_grands_comptes', 'Conseiller Client Grands Comptes'), ('assistante_appui_commercial', 'Assistante Appui Commercial'), ('assistant_technique', 'Assistant Technique')], max_length=30),
        ),
    ]
