# Generated by Django 6.0.6 on 2026-06-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_userprofile_photo_userprofile_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='civilite',
            field=models.CharField(blank=True, choices=[('m', 'M.'), ('mme', 'Mme'), ('mlle', 'Mlle')], max_length=10),
        ),
    ]
