# Generated by Django 6.0.6 on 2026-06-27 17:27. Réordonné à la main : on ajoute le
# M2M, on y copie les données de l'ancienne FK, PUIS on supprime l'ancienne FK,
# pour ne pas perdre les rattachements DR existants (cf. comptes.scoping).

from django.db import migrations, models


def copier_direction_regionale_vers_m2m(apps, schema_editor):
    UserProfile = apps.get_model("comptes", "UserProfile")
    for profile in UserProfile.objects.exclude(direction_regionale=None):
        profile.directions_regionales.add(profile.direction_regionale_id)


def copier_m2m_vers_direction_regionale(apps, schema_editor):
    """Inverse (pour manage.py migrate comptes <précédente>) : reprend la première DR."""
    UserProfile = apps.get_model("comptes", "UserProfile")
    for profile in UserProfile.objects.all():
        premiere_dr = profile.directions_regionales.first()
        if premiere_dr:
            profile.direction_regionale_id = premiere_dr.id
            profile.save(update_fields=["direction_regionale"])


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0007_userprofile_civilite'),
        ('core', '0003_directionregionale_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='directions_regionales',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='core.directionregionale'),
        ),
        migrations.RunPython(copier_direction_regionale_vers_m2m, copier_m2m_vers_direction_regionale),
        migrations.RemoveField(
            model_name='userprofile',
            name='direction_regionale',
        ),
    ]
