# Generated by Django 6.0.6 on 2026-06-28 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0008_directions_regionales_m2m'),
        ('core', '0003_directionregionale_libelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('role_souhaite', models.CharField(blank=True, max_length=150)),
                ('justification', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('entite_souhaitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_acces', to='core.entite')),
            ],
            options={
                'verbose_name': "Demande d'accès",
                'verbose_name_plural': "Demandes d'accès",
                'ordering': ['-cree_le'],
                'db_table': 'accounts_demandeacces',
            },
        ),
    ]
