# Generated by Django 6.0.6 on 2026-06-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0009_demandeacces'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferences_filtres',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
