# Generated by Django 6.0.6 on 2026-07-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0010_userprofile_preferences_filtres'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ccgc_supervisees',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
