# Generated by Django 6.0.6 on 2026-06-29 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_entite_objectif_ca_mensuel_mds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneIndustrielle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Zone industrielle',
                'verbose_name_plural': 'Zones industrielles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TravauxReseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_rattachement', models.CharField(max_length=30, unique=True)),
                ('poste_site', models.CharField(blank=True, max_length=150)),
                ('nom_depart', models.CharField(blank=True, max_length=150)),
                ('date_heure_debut', models.DateTimeField(blank=True, null=True)),
                ('date_heure_fin', models.DateTimeField(blank=True, null=True)),
                ('duree_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('imputation', models.CharField(blank=True, max_length=10)),
                ('puissance_coupee_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('energie_non_distribuee_mwh', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('nb_reclamations', models.PositiveIntegerField(blank=True, null=True)),
                ('nature', models.CharField(blank=True, max_length=150)),
                ('lieu_defaut', models.CharField(blank=True, max_length=150)),
                ('type_manoeuvre', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('direction_regionale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travaux_reseau', to='core.directionregionale')),
                ('zone_industrielle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travaux', to='reseau.zoneindustrielle')),
            ],
            options={
                'verbose_name': 'Travaux réseau',
                'verbose_name_plural': 'Travaux réseau',
                'ordering': ['-date_heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_incident', models.CharField(max_length=30, unique=True)),
                ('poste_site', models.CharField(blank=True, max_length=150)),
                ('nom_depart', models.CharField(blank=True, max_length=150)),
                ('date_heure_debut', models.DateTimeField(blank=True, null=True)),
                ('date_heure_fin', models.DateTimeField(blank=True, null=True)),
                ('duree_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('imputation', models.CharField(blank=True, max_length=10)),
                ('puissance_coupee_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('energie_non_distribuee_mwh', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('nb_reclamations', models.PositiveIntegerField(blank=True, null=True)),
                ('signalisation', models.CharField(blank=True, max_length=100)),
                ('lieu_defaut', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('cause', models.CharField(blank=True, max_length=150)),
                ('code_cause', models.CharField(blank=True, max_length=20)),
                ('ouvrage_id', models.CharField(blank=True, max_length=50)),
                ('direction_regionale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_reseau', to='core.directionregionale')),
                ('zone_industrielle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='reseau.zoneindustrielle')),
            ],
            options={
                'verbose_name': 'Incident réseau',
                'verbose_name_plural': 'Incidents réseau',
                'ordering': ['-date_heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='DepartZoneIndustrielle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste_source', models.CharField(blank=True, max_length=100)),
                ('nom_depart', models.CharField(max_length=150)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departs', to='reseau.zoneindustrielle')),
            ],
            options={
                'verbose_name': 'Départ de zone industrielle',
                'verbose_name_plural': 'Départs de zone industrielle',
                'ordering': ['zone', 'nom_depart'],
                'unique_together': {('zone', 'nom_depart')},
            },
        ),
    ]
