# Generated by Django 6.0.6 on 2026-07-03 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_pad_refraccord_8_chiffres'),
        ('reseau', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheQualiteFourniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('nom_correspondant', models.CharField(max_length=150, verbose_name='Correspondant technique')),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('methode_constat', models.JSONField(blank=True, default=list)),
                ('obs_visuelle', models.TextField(blank=True)),
                ('obs_appareil', models.TextField(blank=True)),
                ('obs_enregistrement', models.TextField(blank=True)),
                ('obs_autre_constat', models.TextField(blank=True)),
                ('frequence_phenomene', models.CharField(blank=True, choices=[('ponctuel', 'Ponctuel (une seule fois)'), ('quotidien', 'Quotidien (tous les jours)'), ('hebdomadaire', 'Hebdomadaire (chaque semaine)'), ('heures_precisees', 'À des heures précises de la journée'), ('irregulier', 'Irrégulier / aléatoire'), ('autre_freq', 'Autre')], max_length=20)),
                ('frequence_detail', models.CharField(blank=True, max_length=255)),
                ('conditions_constat', models.JSONField(blank=True, default=list)),
                ('conditions_detail', models.CharField(blank=True, max_length=255)),
                ('documents_joints', models.JSONField(blank=True, default=list)),
                ('photo_jointe', models.ImageField(blank=True, null=True, upload_to='qualite_fourniture/photos/')),
                ('rapport_joint', models.FileField(blank=True, null=True, upload_to='qualite_fourniture/rapports/')),
                ('documents_observations', models.TextField(blank=True)),
                ('observations_finales', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', "En cours d'analyse"), ('traite', 'Traité')], default='nouveau', max_length=20)),
                ('traite_le', models.DateTimeField(blank=True, null=True)),
                ('note_traitement', models.TextField(blank=True)),
                ('soumis_le', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_qualite_fourniture', to='clients.client')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_qualite_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiche qualité de fourniture',
                'verbose_name_plural': 'Fiches qualité de fourniture',
                'ordering': ['-soumis_le'],
            },
        ),
        migrations.CreateModel(
            name='EvenementQualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin (laisser vide si inconnue)')),
                ('phenomenes', models.JSONField(blank=True, default=list)),
                ('autre_description', models.CharField(blank=True, max_length=255)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='reseau.fichequalitefourniture')),
            ],
            options={
                'verbose_name': 'Événement (fiche qualité)',
                'verbose_name_plural': 'Événements (fiche qualité)',
                'ordering': ['date', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='LienFicheQualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True, verbose_name='Lien actif (accepte encore des soumissions)')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liens_qualite_fourniture', to='clients.client')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liens_qualite_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lien fiche qualité de fourniture',
                'verbose_name_plural': 'Liens fiche qualité de fourniture',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddField(
            model_name='fichequalitefourniture',
            name='lien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches', to='reseau.lienfichequalite'),
        ),
        migrations.CreateModel(
            name='ReleveTension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('heure', models.TimeField(blank=True, null=True)),
                ('u12', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='U12 (V)')),
                ('u23', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='U23 (V)')),
                ('u31', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='U31 (V)')),
                ('v1', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='V1 (V)')),
                ('v2', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='V2 (V)')),
                ('v3', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='V3 (V)')),
                ('appareil_mesure', models.CharField(blank=True, max_length=150)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_tension', to='reseau.fichequalitefourniture')),
            ],
            options={
                'verbose_name': 'Relevé de tension',
                'verbose_name_plural': 'Relevés de tension',
                'ordering': ['date', 'heure'],
            },
        ),
    ]
