# Generated by Django 6.0.6 on 2026-06-24 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numfact', models.CharField(blank=True, max_length=30)),
                ('typfact', models.CharField(max_length=5)),
                ('consommation_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('montant_facture_ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('montant_tva_11', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('montant_tva_20', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('penalite_ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='clients.abonnement')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='clients.client')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='core.periode')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'billing_facture',
            },
        ),
        migrations.CreateModel(
            name='Recouvrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_facture', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recouvrements', to='clients.client')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recouvrements', to='facturation.facture')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recouvrements', to='core.periode')),
            ],
            options={
                'verbose_name': 'Recouvrement',
                'verbose_name_plural': 'Recouvrements',
                'db_table': 'billing_recouvrement',
            },
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['periode', 'typfact'], name='billing_fac_periode_cca3e8_idx'),
        ),
    ]
